### PR TITLE
RFC: Idris and Nix packaging, general cleanup

### PR DESCRIPTION
**Pull request by yurrriq**
Some of the decisions herein are rather subjective, namely the cosmetic changes, but I'm curious to learn what you think of this reorganization generally. Cheers for this project, by the way.

Also, do you have any desire to try to do a mashup of this and [States](https://github.com/edwinb/states)? The ideas seem compatible enough, probably. If you haven't read that paper, I think you'd enjoy it. ~~I can try to find a link, if you want.~~ **Edit**: Here's a link to [a draft of the paper](https://eb.host.cs.st-andrews.ac.uk/drafts/states-all-the-way.pdf).

### CODE REVIEW

**Comment by ctford** [comment]
Hi @yurrriq,

I appreciate the help. Apart from all the improvements, it was also handy for me to learn from (for example, I wasn't previously familiar with the bang pattern syntax in do notation or how to specify docstrings). Your suggestions look generally good to me and there are a couple I'm neutral on (indentation, literate style). I might take a little longer to look over everything though before I merge.

Is Nix the standard way folks package Idris at the moment? I must admit, I don't use it myself at the moment, though I've been planning to learn it. Nix seems like a good fit.

Thanks for the link to the paper - I haven't read that specifically, but I've been reading previews of [Edwin's upcoming book](https://www.manning.com/books/type-driven-development-with-idris) and I think it's the same examples. I used his door protocol as a reference, although my examples have drifted a little from his ideas. I may yet revert back so that it's easier for those who read the book to follow along.

I'm unsure as to whether a States mashup is a good idea - I'm not really sure where Edwin is going with States. For me part of the cuteness of FSM as it is is that it's quite small, and thus serve as a better example for newcomers to Idris. Having said that, I certainly don't object to any of FSM's ideas being made use of in other projects! If the FSM type provider were useful as an example or feature for States, I'd be happy for it to end up there, but I would likely still want to play with FSM on the side.

What kind of mashup were you thinking of?

Chris

**Comment by yurrriq** [comment]
Quick reply while I'm mobile.

I'd happy to split this up into separate concerns, if you like. I know I went and touched nearly everything...

As mentioned on IRC, there's no real standard for packaging yet. The [ipkg spec](http://docs.idris-lang.org/en/latest/reference/packages.html#ref-sect-packages) is well defined and `idris` interacts with `.ipkg` files in a standard way. Personally, I use Nix for nearly everything and find it's great for cross-platform, reproducible builds.

The point of the docstrings wasn't so much to be literate (though I do have a penchant for LP) but rather to be more informative in the REPL via `:doc` et al.

**Comment by yurrriq** [comment]
More info about the so-called (and impossible to search for) !-notation
- http://docs.idris-lang.org/en/latest/tutorial/interfaces.html#notation

More info re: ipkg
- http://docs.idris-lang.org/en/latest/tutorial/packages.html
- http://docs.idris-lang.org/en/latest/reference/packages.html#ref-sect-packages

**Comment by ctford** [comment]
No need to split into separate concerns. The commits are nice and distinct.

**Comment by yurrriq** [comment]
:+1: Basically I thought it would be cool to generate (effectful) States types from text files, as in FSM. I totally understand your liking the smallness of FSM and its newcomer-friendliness. A States type provider would probably be best suited for a separate project.

**Comment by yurrriq** [comment]
Oh wow, I forgot I changed it to `Example.lidr`... Thanks for merging!

**Comment by ctford** [comment]
An interesting side effect of your changes is that I needed to start the repl in src to get evaluating Example.lidr to work. Another is that the vim plugin doesn't properly recognise .lidrs. I might add some repl experimentation instructions to help folks with those.

**Comment by yurrriq** [comment]
That's unfortunate. `.lidr` support is great in Emacs fwiw..

**Comment by yurrriq** [comment]
Re: repl. You could try something like `idris -i src -i example` from the project root.

**Pull request merged**
